Step3
WoodMechanics/wood-forms pull request #5
Opened 2023-12-23 10:02 UTC by Winechicken

2024-01-08 10:30 UTC, SavaCool122 requested changes

2024-01-08 10:30 UTC, SavaCool122 commented on src/App.vue
> +
extra space, don't forget to use prettier

2024-01-08 10:30 UTC, SavaCool122 commented on src/App.vue
>  </template>
forgot to delete styles after deleting tags

2024-01-08 10:30 UTC, SavaCool122 commented on src/components/about/header/Header.vue
> +<!-- eslint-disable vue/multi-word-component-names -->
lest move this rule from comment to `.eslintrc.cjs`

2024-01-08 10:30 UTC, SavaCool122 commented on src/components/about/header/Header.vue
> +@import url('https://fonts.googleapis.com/css2?family=Red+Hat+Display&display=swap');
let's not use Google font imports. These are unnecessary network requests when loading the page. it is better to download and connect them locally

2024-01-08 10:30 UTC, SavaCool122 commented on src/components/about/header/Header.vue
> +a {
we can use modern css nesting 

```css
a {
	text-decoration: none;
	color: #121212;
	margin: 10px 40px;
	font-size: 20px;
	
	&:hover {
	  transition-duration: .4s;
	  color: #28297a;
	  text-shadow: 0 0 1px #28297a;
        }
}
```

and for .mainLink same

2024-01-08 10:30 UTC, SavaCool122 commented on src/components/common/LinkButton.vue
> +<script setup></script>
les's move mainLink from Header.vue to this component and reuse it in Header.vue

2024-01-11 07:25 UTC, SavaCool122 commented on src/App.vue
> +
adasdasda

2024-01-11 07:38 UTC, Winechicken commented on src/App.vue
> +
Done, sorry, never happen again

2024-01-11 07:38 UTC, Winechicken commented on src/App.vue
>  </template>
Done, sorry, never happen again

2024-01-11 07:38 UTC, Winechicken commented on src/components/about/header/Header.vue
> +<!-- eslint-disable vue/multi-word-component-names -->
Done, I'll delete the comments

2024-01-11 07:38 UTC, Winechicken commented on src/components/about/header/Header.vue
> +@import url('https://fonts.googleapis.com/css2?family=Red+Hat+Display&display=swap');
Ok, I'll manage it

2024-01-11 07:38 UTC, Winechicken commented on src/components/about/header/Header.vue
> +a {
Done

2024-01-11 07:38 UTC, Winechicken commented on src/components/common/LinkButton.vue
> +<script setup></script>
Done

2024-01-18 07:15 UTC, SavaCool122 requested changes

2024-01-18 07:15 UTC, SavaCool122 commented on src/App.vue
>  		padding-right: calc(var(--section-gap) / 2);
this css variable dont exist

2024-01-18 07:18 UTC, SavaCool122 requested changes

2024-01-18 07:18 UTC, SavaCool122 commented on src/assets/tree1.png
please replace with svg

2024-01-18 07:22 UTC, SavaCool122 commented on src/components/about/header/Header.vue
> +				<LinkButton></LinkButton>
please replace with single tag `<LinkButton></LinkButton>` with `<LinkButton />`

2024-01-18 07:26 UTC, SavaCool122 commented on src/pages/HomePage.vue
> +body {
lest move this code fragment to wrapper component

2024-01-18 07:37 UTC, SavaCool122 commented on src/components/about/header/Header.vue
> +	<body>
please remove boy from header

2024-02-01 07:14 UTC, Winechicken commented on src/components/about/header/Header.vue
> +	<body>
done

2024-02-01 07:14 UTC, Winechicken commented on src/pages/HomePage.vue
> +body {
done

2024-02-01 07:14 UTC, Winechicken commented on src/components/about/header/Header.vue
> +				<LinkButton></LinkButton>
done and commited

2024-02-01 07:15 UTC, Winechicken commented on src/assets/tree1.png
all imgs are in svg now

2024-02-01 07:16 UTC, SavaCool122 approved these changes

2024-02-01 07:16 UTC, merged